version: '3.7'

networks:
  my-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: alpujarraalmeria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Monta el directorio init
    networks:
      - my-network

  express:
    build: ./ProyectoServidor
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my-network

  react:
    build: ./proyecto
    restart: always
    ports:
      - "80:80"
    depends_on:
      - express
    networks:
      - my-network
volumes:
  postgres_data:
