services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: alpujarra_almeria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  express:
    build: ./ProyectoServidor
    volumes:
      - /usr/src/app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  react:
    build: ./proyecto
    volumes:
      - /usr/src/app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - express

volumes:
  postgres_data:
